#include "paint.hpp"
#include "layout.hpp"

namespace ui::paint {
using namespace app;
void fillRound(HDC dc, RECT r, COLORREF color, int radius, COLORREF stroke) { HBRUSH brush=CreateSolidBrush(color); HPEN pen=CreatePen(PS_SOLID,1,stroke==CLR_INVALID?color:stroke); HGDIOBJ ob=SelectObject(dc,brush),op=SelectObject(dc,pen); RoundRect(dc,r.left,r.top,r.right,r.bottom,radius,radius); SelectObject(dc,ob); SelectObject(dc,op); DeleteObject(brush); DeleteObject(pen); }
static void text(HDC dc,const wchar_t* value,RECT r,UINT flags,COLORREF color,HFONT font){SetBkMode(dc,TRANSPARENT);SetTextColor(dc,color);HGDIOBJ old=SelectObject(dc,font);DrawTextW(dc,value,-1,&r,flags);SelectObject(dc,old);}
static RECT iconBox(const RECT& r){int cx=(r.left+r.right)/2,cy=(r.top+r.bottom)/2;return layout::rect(cx-12,cy-12,cx+12,cy+12);}
RECT scrollTrack(const RECT& card){return layout::rect(card.right-14,card.top+7,card.right-6,card.bottom-7);}
static int visibleLines(const RECT& card){return std::max<int>(1,int((card.bottom-card.top-14)/18));}
static RECT scrollThumb(HWND edit,const RECT& card){RECT t=scrollTrack(card);int total=std::max(1,int(SendMessageW(edit,EM_GETLINECOUNT,0,0))),page=visibleLines(card),th=std::max<int>(28,(t.bottom-t.top)*page/total),travel=std::max<int>(0,(t.bottom-t.top)-th),maxFirst=std::max<int>(1,total-page),first=std::clamp<int>(int(SendMessageW(edit,EM_GETFIRSTVISIBLELINE,0,0)),0,maxFirst);int top=t.top+first*travel/maxFirst;return layout::rect(t.left,top,t.right,top+th);}
bool hasScroll(const AppState& s, HWND edit){return int(SendMessageW(edit,EM_GETLINECOUNT,0,0))>visibleLines(edit==s.input?s.inputRect:s.outputRect);}
static void paintScroll(HDC dc,const AppState& s,HWND edit,const RECT& card){if(!IsWindowVisible(edit)||!hasScroll(s,edit))return;RECT t=scrollTrack(card);fillRound(dc,t,RGB(229,241,236),8);fillRound(dc,scrollThumb(edit,card),s.theme,8);}
void scrollTo(AppState& s,HWND edit,const RECT& card,int y){int total=std::max(1,int(SendMessageW(edit,EM_GETLINECOUNT,0,0))),page=visibleLines(card),maxFirst=std::max(0,total-page),first=int(SendMessageW(edit,EM_GETFIRSTVISIBLELINE,0,0));RECT t=scrollTrack(card),thumb=scrollThumb(edit,card);int travel=std::max<int>(1,(t.bottom-t.top)-(thumb.bottom-thumb.top));int target=std::clamp<int>((y-t.top-(thumb.bottom-thumb.top)/2)*maxFirst/travel,0,maxFirst);SendMessageW(edit,EM_LINESCROLL,0,target-first);InvalidateRect(s.hwnd,&card,FALSE);}
static void toggle(HDC dc,RECT r,bool on,COLORREF accent){fillRound(dc,r,on?accent:RGB(200,211,206),18);HBRUSH b=CreateSolidBrush(RGB(255,255,255));HGDIOBJ old=SelectObject(dc,b);int d=r.bottom-r.top-4,x=on?r.right-d-2:r.left+2;Ellipse(dc,x,r.top+2,x+d,r.bottom-2);SelectObject(dc,old);DeleteObject(b);}
static void headerClose(HDC dc,RECT r){HPEN p=CreatePen(PS_SOLID,2,RGB(113,129,122));HGDIOBJ o=SelectObject(dc,p);MoveToEx(dc,r.left+9,r.top+8,nullptr);LineTo(dc,r.right-9,r.bottom-8);MoveToEx(dc,r.right-9,r.top+8,nullptr);LineTo(dc,r.left+9,r.bottom-8);SelectObject(dc,o);DeleteObject(p);}
void paint(HDC dc,AppState& s,svg::Renderer& renderer){
    RECT client;GetClientRect(s.hwnd,&client);fillRound(dc,layout::rect(0,0,client.right,client.bottom),RGB(255,255,255),14,kBorder);renderer.draw(dc,svg::Asset::Logo,layout::rect(15,8,49,42),s.theme,true);
    auto title=[&](RECT r,int id){fillRound(dc,r,s.hot==id?(s.pressed==id?RGB(205,236,221):RGB(225,245,237)):RGB(255,255,255),6);};title(s.settingsButton,Settings);title(s.minButton,Minimize);title(s.closeButton,Close);renderer.draw(dc,svg::Asset::Settings,iconBox(s.settingsButton),s.theme,false);text(dc,L"–",s.minButton,DT_CENTER|DT_VCENTER|DT_SINGLELINE,RGB(113,129,122),s.font);headerClose(dc,s.closeButton);
    if(s.settings){fillRound(dc,s.settingsRect,kSoft,10,kBorder);text(dc,L"开机自启动",layout::rect(s.settingsRect.left+16,s.startupCheck.top-2,s.startupCheck.left-14,s.startupCheck.bottom+3),DT_SINGLELINE|DT_VCENTER,kText,s.font);toggle(dc,s.startupCheck,s.startup,s.theme);text(dc,L"悬浮在最上层",layout::rect(s.settingsRect.left+16,s.topmostCheck.top-2,s.topmostCheck.left-14,s.topmostCheck.bottom+3),DT_SINGLELINE|DT_VCENTER,kText,s.font);toggle(dc,s.topmostCheck,s.topmost,s.theme);HBRUSH cb=CreateSolidBrush(s.theme);HGDIOBJ old=SelectObject(dc,cb);Ellipse(dc,s.colorButton.left,s.colorButton.top,s.colorButton.right,s.colorButton.bottom);SelectObject(dc,old);DeleteObject(cb);text(dc,L"主题颜色",layout::rect(s.settingsRect.left+16,s.colorButton.top-2,s.colorButton.left-14,s.colorButton.bottom+3),DT_SINGLELINE|DT_VCENTER,kText,s.font);if(s.colorPicker){static constexpr COLORREF colors[]={RGB(45,212,163),RGB(66,133,244),RGB(154,102,255),RGB(245,140,66),RGB(235,87,87)};for(size_t i=0;i<s.presetColors.size();++i){HBRUSH b=CreateSolidBrush(colors[i]);HGDIOBJ o=SelectObject(dc,b);const RECT& r=s.presetColors[i];Ellipse(dc,r.left,r.top,r.right,r.bottom);SelectObject(dc,o);DeleteObject(b);}fillRound(dc,s.applyColor,s.theme,6);text(dc,L"应用",s.applyColor,DT_CENTER|DT_VCENTER|DT_SINGLELINE,RGB(255,255,255),s.font);}}
    fillRound(dc,s.inputRect,RGB(255,255,255),10,kBorder);if(GetWindowTextLengthW(s.input)>0){fillRound(dc,s.clearButton,s.hot==ClearInput?RGB(207,245,229):RGB(255,255,255),14);renderer.draw(dc,svg::Asset::Cancel,s.clearButton,s.theme,true);}paintScroll(dc,s,s.input,s.inputRect);
    if(!s.result.empty()){fillRound(dc,s.outputRect,RGB(255,255,255),10,RGB(207,235,223));fillRound(dc,s.deleteButton,s.hot==DeleteOutput?RGB(207,245,229):RGB(255,255,255),14);renderer.draw(dc,svg::Asset::Cancel,s.deleteButton,s.theme,true);fillRound(dc,s.copyButton,s.hot==CopyOutput?RGB(207,245,229):RGB(255,255,255),14);renderer.draw(dc,svg::Asset::Copy,s.copyButton,s.theme,true);if(s.copied){RECT tip=layout::rect(s.outputRect.right-122,s.outputRect.top+8,s.outputRect.right-64,s.outputRect.top+30);fillRound(dc,tip,s.theme,8);text(dc,L"已复制",tip,DT_CENTER|DT_VCENTER|DT_SINGLELINE,RGB(255,255,255),s.font);}paintScroll(dc,s,s.output,s.outputRect);}
}
}
