#include "win32_window.hpp"
#include "app_state.hpp"
#include "icon_theming.hpp"
#include "layout.hpp"
#include "paint.hpp"
#include "system_integration.hpp"
#include "resource.h"
#include <cwctype>
#include <shellapi.h>
#pragma comment(lib,"Comctl32.lib")
#pragma comment(lib,"Shell32.lib")

namespace win {
using namespace app; static AppState g_state; static svg::Renderer* g_renderer{}; constexpr int kBubbleSize=56;
static void hideControlsForBubble(){for(HWND c:{g_state.input,g_state.output,g_state.colorInput,g_state.filterInput,g_state.clearOverlay,g_state.copyOverlay,g_state.deleteOverlay})ShowWindow(c,SW_HIDE);}
static void collapseToBubble(){RECT b{};GetWindowRect(g_state.hwnd,&b);g_state.expandedSize={b.right-b.left,b.bottom-b.top};g_state.compact=true;hideControlsForBubble();SetWindowRgn(g_state.hwnd,nullptr,FALSE);DWM_WINDOW_CORNER_PREFERENCE corner=DWMWCP_DONOTROUND;DWMNCRENDERINGPOLICY ncr=DWMNCRP_DISABLED;DwmSetWindowAttribute(g_state.hwnd,DWMWA_WINDOW_CORNER_PREFERENCE,&corner,sizeof(corner));DwmSetWindowAttribute(g_state.hwnd,DWMWA_NCRENDERING_POLICY,&ncr,sizeof(ncr));SetWindowLongPtrW(g_state.hwnd,GWL_EXSTYLE,GetWindowLongPtrW(g_state.hwnd,GWL_EXSTYLE)|WS_EX_LAYERED);SetWindowPos(g_state.hwnd,nullptr,b.left,b.top,kBubbleSize,kBubbleSize,SWP_NOZORDER|SWP_NOACTIVATE|SWP_FRAMECHANGED);ui::paint::paintCompactLayered(g_state.hwnd,*g_renderer,g_state.theme,g_state.darkMode);}
static void expandFromBubble(){DWM_WINDOW_CORNER_PREFERENCE corner=DWMWCP_ROUND;DWMNCRENDERINGPOLICY ncr=DWMNCRP_ENABLED;DwmSetWindowAttribute(g_state.hwnd,DWMWA_NCRENDERING_POLICY,&ncr,sizeof(ncr));DwmSetWindowAttribute(g_state.hwnd,DWMWA_WINDOW_CORNER_PREFERENCE,&corner,sizeof(corner));SetWindowLongPtrW(g_state.hwnd,GWL_EXSTYLE,GetWindowLongPtrW(g_state.hwnd,GWL_EXSTYLE)&~WS_EX_LAYERED);g_state.compact=false;SetWindowPos(g_state.hwnd,nullptr,0,0,g_state.expandedSize.cx,g_state.expandedSize.cy,SWP_NOMOVE|SWP_NOZORDER|SWP_NOACTIVATE|SWP_FRAMECHANGED);ui::layout::compute(g_state,true);ShowWindow(g_state.input,SW_SHOW);ShowWindow(g_state.clearOverlay,GetWindowTextLengthW(g_state.input)?SW_SHOW:SW_HIDE);SetFocus(g_state.input);InvalidateRect(g_state.hwnd,nullptr,FALSE);}
static int buttonAt(POINT p){if(ui::layout::contains(g_state.infoButton,p))return Info;if(ui::layout::contains(g_state.settingsButton,p))return Settings;if(ui::layout::contains(g_state.minButton,p))return Minimize;if(ui::layout::contains(g_state.closeButton,p))return Close;if(g_state.infoPage){if(ui::layout::contains(g_state.bilibiliLink,p))return Bilibili;if(ui::layout::contains(g_state.githubLink,p))return Github;if(ui::layout::contains(g_state.supportButton,p))return Support;}if(ui::layout::contains(g_state.clearButton,p)&&GetWindowTextLengthW(g_state.input))return ClearInput;if(ui::layout::contains(g_state.copyButton,p)&&!g_state.result.empty())return CopyOutput;if(ui::layout::contains(g_state.deleteButton,p)&&!g_state.result.empty())return DeleteOutput;if(ui::layout::contains(g_state.colorButton,p))return Color;return None;}
static bool filterHit(POINT p,size_t& index,bool& deleting){if(!g_state.settings)return false;for(size_t i=0;i<g_state.filters.size();++i){auto& item=g_state.filters[i];if(!item.builtin&&ui::layout::contains(item.deleteButton,p)){index=i;deleting=true;return true;}if(ui::layout::contains(item.button,p)){index=i;deleting=false;return true;}}return false;}
static std::wstring filteredText(const std::wstring& raw){std::wstring out;for(size_t pos=0;pos<raw.size();){size_t longest=0;for(const auto& item:g_state.filters)if(item.selected&&!item.text.empty()&&raw.compare(pos,item.text.size(),item.text)==0)longest=std::max(longest,item.text.size());if(longest)pos+=longest;else out.push_back(raw[pos++]);}return out;}
void processInput(){std::wstring raw=sys::text(g_state.input);if(raw.empty())return;g_state.result=filteredText(raw);SetWindowTextW(g_state.output,g_state.result.c_str());ui::layout::compute(g_state);SetFocus(g_state.input);}
static void addFilter(){std::wstring value=sys::text(g_state.filterInput);if(value.empty()||std::all_of(value.begin(),value.end(),[](wchar_t c){return std::iswspace(c)!=0;}))return;bool exists=std::any_of(g_state.filters.begin(),g_state.filters.end(),[&](const FilterItem& item){return item.text==value;});if(!exists)g_state.filters.push_back({value,true,false});SetWindowTextW(g_state.filterInput,L"");ui::layout::compute(g_state);SetFocus(g_state.filterInput);}
static LRESULT CALLBACK actionProc(HWND h,UINT m,WPARAM w,LPARAM l,UINT_PTR,DWORD_PTR){int id=h==g_state.clearOverlay?ClearInput:h==g_state.copyOverlay?CopyOutput:DeleteOutput;if(m==WM_MOUSEMOVE){if(g_state.hot!=id){g_state.hot=id;InvalidateRect(h,nullptr,FALSE);}TRACKMOUSEEVENT t{sizeof(t),TME_LEAVE,h,0};TrackMouseEvent(&t);}if(m==WM_MOUSELEAVE&&g_state.hot==id){g_state.hot=None;InvalidateRect(h,nullptr,FALSE);}if(m==WM_SETCURSOR){SetCursor(LoadCursor(nullptr,IDC_HAND));return TRUE;}return DefSubclassProc(h,m,w,l);}
static LRESULT CALLBACK editProc(HWND h,UINT m,WPARAM w,LPARAM l,UINT_PTR,DWORD_PTR){if(m==WM_KEYDOWN&&w==VK_RETURN&&!(GetKeyState(VK_SHIFT)&0x8000)){processInput();return 0;}if(m==WM_KEYDOWN&&w==L'A'&&(GetKeyState(VK_CONTROL)&0x8000)){SendMessageW(h,EM_SETSEL,0,-1);return 0;}if(m==WM_CHAR&&(w==1||w==VK_RETURN))return 0;if(m==WM_MOUSEWHEEL){SendMessageW(h,EM_LINESCROLL,0,-GET_WHEEL_DELTA_WPARAM(w)/WHEEL_DELTA*3);PostMessageW(g_state.hwnd,WM_APP+1,0,0);return 0;}if(m==WM_VSCROLL||m==WM_KEYUP)PostMessageW(g_state.hwnd,WM_APP+1,0,0);return DefSubclassProc(h,m,w,l);}
static LRESULT CALLBACK filterProc(HWND h,UINT m,WPARAM w,LPARAM l,UINT_PTR,DWORD_PTR){if(m==WM_KEYDOWN&&w==VK_RETURN){addFilter();return 0;}if(m==WM_CHAR&&w==VK_RETURN)return 0;return DefSubclassProc(h,m,w,l);}
static LRESULT CALLBACK wndProc(HWND h,UINT m,WPARAM w,LPARAM l){
if(g_state.compact){if(m==WM_PAINT){PAINTSTRUCT p{};BeginPaint(h,&p);EndPaint(h,&p);ui::paint::paintCompactLayered(h,*g_renderer,g_state.theme,g_state.darkMode);return 0;}if(m==WM_LBUTTONDOWN){GetCursorPos(&g_state.bubbleStartCursor);RECT b{};GetWindowRect(h,&b);g_state.bubbleStartWindow={b.left,b.top};g_state.bubblePointerDown=true;g_state.bubbleMoved=false;SetCapture(h);return 0;}if(m==WM_MOUSEMOVE&&g_state.bubblePointerDown){POINT c{};GetCursorPos(&c);int dx=c.x-g_state.bubbleStartCursor.x,dy=c.y-g_state.bubbleStartCursor.y;if(dx||dy){g_state.bubbleMoved=true;SetWindowPos(h,nullptr,g_state.bubbleStartWindow.x+dx,g_state.bubbleStartWindow.y+dy,0,0,SWP_NOSIZE|SWP_NOZORDER|SWP_NOACTIVATE);}return 0;}if(m==WM_LBUTTONUP&&g_state.bubblePointerDown){g_state.bubblePointerDown=false;ReleaseCapture();if(!g_state.bubbleMoved)expandFromBubble();return 0;}if(m==WM_SETCURSOR){SetCursor(LoadCursor(nullptr,IDC_HAND));return TRUE;}if(m==WM_NCHITTEST)return HTCLIENT;}
if(!g_state.compact&&m==WM_LBUTTONDOWN){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(ui::layout::contains(g_state.minButton,p)){collapseToBubble();return 0;}}
if(m==WM_COMMAND&&(HWND)l==g_state.colorInput&&HIWORD(w)==EN_CHANGE&&g_state.settings&&g_state.colorPicker){COLORREF c;if(theming::parseColor(sys::text(g_state.colorInput),c)){g_state.theme=c;InvalidateRect(h,nullptr,FALSE);}return 0;}
if(m==WM_LBUTTONDOWN){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(ui::layout::contains(g_state.darkModeButton,p)){g_state.darkMode=!g_state.darkMode;InvalidateRect(h,nullptr,FALSE);return 0;}if(ui::layout::contains(g_state.settingsButton,p)&&g_state.infoPage){g_state.infoPage=false;g_state.settings=true;g_state.colorPicker=false;ui::layout::compute(g_state);return 0;}if(ui::layout::contains(g_state.infoButton,p)){g_state.infoPage=!g_state.infoPage;g_state.settings=false;g_state.colorPicker=false;ui::layout::compute(g_state);return 0;}if(g_state.infoPage){if(ui::layout::contains(g_state.supportButton,p)){g_state.supportOpen=!g_state.supportOpen;ui::layout::compute(g_state);return 0;}if(ui::layout::contains(g_state.bilibiliLink,p)){ShellExecuteW(h,L"open",L"https://space.bilibili.com/443655072?spm_id_from=333.1007.0.0",nullptr,nullptr,SW_SHOWNORMAL);return 0;}if(ui::layout::contains(g_state.githubLink,p)){ShellExecuteW(h,L"open",L"https://github.com/buyinakili/TextClean",nullptr,nullptr,SW_SHOWNORMAL);return 0;}}}
if(m==WM_SETCURSOR){POINT p;GetCursorPos(&p);ScreenToClient(h,&p);if(ui::layout::contains(g_state.darkModeButton,p)){SetCursor(LoadCursor(nullptr,IDC_HAND));return TRUE;}int id=buttonAt(p);if(id==Info||id==Bilibili||id==Github||id==Support){SetCursor(LoadCursor(nullptr,IDC_HAND));return TRUE;}}
switch(m){
case WM_CREATE:{g_state.hwnd=h;g_state.font=CreateFontW(-14,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Segoe UI");g_state.titleFont=CreateFontW(-14,0,0,0,FW_SEMIBOLD,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Segoe UI");g_state.input=CreateWindowExW(0,L"EDIT",L"",WS_CHILD|WS_VISIBLE|WS_VSCROLL|ES_MULTILINE|ES_AUTOVSCROLL|ES_WANTRETURN,0,0,0,0,h,nullptr,nullptr,nullptr);g_state.output=CreateWindowExW(0,L"EDIT",L"",WS_CHILD|WS_VSCROLL|ES_MULTILINE|ES_AUTOVSCROLL|ES_READONLY,0,0,0,0,h,nullptr,nullptr,nullptr);g_state.colorInput=CreateWindowExW(0,L"EDIT",L"#2DD4A3",WS_CHILD|ES_AUTOHSCROLL,0,0,0,0,h,nullptr,nullptr,nullptr);g_state.filterInput=CreateWindowExW(0,L"EDIT",L"",WS_CHILD|ES_AUTOHSCROLL,0,0,0,0,h,nullptr,nullptr,nullptr);SendMessageW(g_state.filterInput,EM_SETCUEBANNER,TRUE,reinterpret_cast<LPARAM>(L"添加过滤内容"));g_state.clearOverlay=CreateWindowExW(0,L"BUTTON",L"",WS_CHILD|BS_OWNERDRAW,0,0,0,0,h,(HMENU)1001,nullptr,nullptr);g_state.copyOverlay=CreateWindowExW(0,L"BUTTON",L"",WS_CHILD|BS_OWNERDRAW,0,0,0,0,h,(HMENU)1002,nullptr,nullptr);g_state.deleteOverlay=CreateWindowExW(0,L"BUTTON",L"",WS_CHILD|BS_OWNERDRAW,0,0,0,0,h,(HMENU)1003,nullptr,nullptr);for(HWND c:{g_state.input,g_state.output,g_state.colorInput,g_state.filterInput})SendMessageW(c,WM_SETFONT,(WPARAM)g_state.font,TRUE);ShowScrollBar(g_state.input,SB_VERT,FALSE);ShowScrollBar(g_state.output,SB_VERT,FALSE);SetWindowSubclass(g_state.input,editProc,1,0);SetWindowSubclass(g_state.output,editProc,2,0);SetWindowSubclass(g_state.filterInput,filterProc,6,0);SetWindowSubclass(g_state.clearOverlay,actionProc,3,0);SetWindowSubclass(g_state.copyOverlay,actionProc,4,0);SetWindowSubclass(g_state.deleteOverlay,actionProc,5,0);g_state.startup=sys::startupEnabled();ui::layout::compute(g_state,true);return 0;}
case WM_CTLCOLOREDIT:case WM_CTLCOLORSTATIC:{HDC dc=(HDC)w;static HBRUSH brush{};static COLORREF brushColor=CLR_INVALID;COLORREF background=g_state.darkMode?RGB(31,35,40):RGB(255,255,255);if(brushColor!=background){if(brush)DeleteObject(brush);brush=CreateSolidBrush(background);brushColor=background;}SetTextColor(dc,g_state.darkMode?RGB(255,255,255):kText);SetBkColor(dc,background);return(LRESULT)brush;}case WM_ERASEBKGND:return 1;
case WM_PAINT:{PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(dc);HBITMAP bmp=CreateCompatibleBitmap(dc,c.right,c.bottom);HGDIOBJ old=SelectObject(mem,bmp);ui::paint::paint(mem,g_state,*g_renderer);BitBlt(dc,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bmp);DeleteDC(mem);EndPaint(h,&ps);return 0;}
case WM_DRAWITEM:{auto*d=reinterpret_cast<DRAWITEMSTRUCT*>(l);if(d->CtlID==1001||d->CtlID==1002||d->CtlID==1003){int id=d->CtlID==1001?ClearInput:d->CtlID==1002?CopyOutput:DeleteOutput;RECT r{0,0,d->rcItem.right-d->rcItem.left,d->rcItem.bottom-d->rcItem.top};ui::paint::fillRound(d->hDC,r,g_state.hot==id?RGB(207,245,229):RGB(255,255,255),14);g_renderer->draw(d->hDC,id==CopyOutput?svg::Asset::Copy:svg::Asset::Cancel,r,g_state.theme,true);return TRUE;}break;}
case WM_COMMAND:if((HWND)l==g_state.clearOverlay&&HIWORD(w)==BN_CLICKED){SendMessageW(g_state.input,EM_SETSEL,0,-1);SendMessageW(g_state.input,EM_REPLACESEL,TRUE,(LPARAM)L"");SetFocus(g_state.input);return 0;}if((HWND)l==g_state.copyOverlay&&HIWORD(w)==BN_CLICKED){sys::copyResult(g_state);InvalidateRect(h,nullptr,FALSE);return 0;}if((HWND)l==g_state.input&&HIWORD(w)==EN_CHANGE){int needed=ui::layout::heightFor(g_state.input,kInputMin,kInputMax);if(needed!=g_state.inputHeight)ui::layout::compute(g_state);else{ShowWindow(g_state.clearOverlay,GetWindowTextLengthW(g_state.input)?SW_SHOW:SW_HIDE);InvalidateRect(h,&g_state.clearButton,FALSE);}return 0;}break;
case WM_APP+1:InvalidateRect(h,&g_state.inputRect,FALSE);if(!g_state.result.empty())InvalidateRect(h,&g_state.outputRect,FALSE);return 0;
case WM_LBUTTONDOWN:{POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(ui::paint::hasScroll(g_state,g_state.input)&&ui::layout::contains(ui::paint::scrollTrack(g_state.inputRect),p)){g_state.dragScroll=g_state.input;SetCapture(h);ui::paint::scrollTo(g_state,g_state.input,g_state.inputRect,p.y);return 0;}if(!g_state.result.empty()&&ui::paint::hasScroll(g_state,g_state.output)&&ui::layout::contains(ui::paint::scrollTrack(g_state.outputRect),p)){g_state.dragScroll=g_state.output;SetCapture(h);ui::paint::scrollTo(g_state,g_state.output,g_state.outputRect,p.y);return 0;}size_t i{};bool deleting{};if(filterHit(p,i,deleting)){if(deleting)g_state.filters.erase(g_state.filters.begin()+i);else g_state.filters[i].selected=!g_state.filters[i].selected;g_state.hotFilter=-1;ui::layout::compute(g_state);return 0;}if(g_state.settings&&ui::layout::contains(g_state.colorButton,p)){g_state.colorPicker=!g_state.colorPicker;ui::layout::compute(g_state);return 0;}if(g_state.settings&&g_state.colorPicker)for(size_t n=0;n<g_state.presetColors.size();++n)if(ui::layout::contains(g_state.presetColors[n],p)){g_state.theme=theming::preset(n);wchar_t hex[8];swprintf_s(hex,L"#%02X%02X%02X",GetRValue(g_state.theme),GetGValue(g_state.theme),GetBValue(g_state.theme));SetWindowTextW(g_state.colorInput,hex);InvalidateRect(h,nullptr,FALSE);return 0;}if(ui::layout::contains(g_state.settingsButton,p)){g_state.settings=!g_state.settings;g_state.colorPicker=false;ui::layout::compute(g_state);return 0;}if(ui::layout::contains(g_state.closeButton,p)){PostMessageW(h,WM_CLOSE,0,0);return 0;}if(ui::layout::contains(g_state.clearButton,p)&&GetWindowTextLengthW(g_state.input)){SendMessageW(g_state.input,EM_SETSEL,0,-1);SendMessageW(g_state.input,EM_REPLACESEL,TRUE,(LPARAM)L"");SetFocus(g_state.input);return 0;}if(ui::layout::contains(g_state.copyButton,p)&&!g_state.result.empty()){sys::copyResult(g_state);InvalidateRect(h,nullptr,FALSE);return 0;}if(ui::layout::contains(g_state.deleteButton,p)&&!g_state.result.empty()){g_state.result.clear();SetWindowTextW(g_state.output,L"");ui::layout::compute(g_state);return 0;}if(g_state.settings&&ui::layout::contains(g_state.startupCheck,p)){sys::setStartup(g_state,!g_state.startup);InvalidateRect(h,nullptr,FALSE);return 0;}if(g_state.settings&&ui::layout::contains(g_state.topmostCheck,p)){g_state.topmost=!g_state.topmost;SetWindowPos(h,g_state.topmost?HWND_TOPMOST:HWND_NOTOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE);InvalidateRect(h,nullptr,FALSE);return 0;}if(p.y<kHeaderHeight){ReleaseCapture();SendMessageW(h,WM_NCLBUTTONDOWN,HTCAPTION,0);return 0;}break;}
case WM_MOUSEMOVE:{POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(g_state.dragScroll){ui::paint::scrollTo(g_state,g_state.dragScroll,g_state.dragScroll==g_state.input?g_state.inputRect:g_state.outputRect,p.y);return 0;}size_t i{};bool deleting{};if(filterHit(p,i,deleting)){if(g_state.hot!=None||g_state.hotFilter!=(int)i){g_state.hot=None;g_state.hotFilter=(int)i;InvalidateRect(h,nullptr,FALSE);}}else{int hot=buttonAt(p);if(hot!=g_state.hot||g_state.hotFilter!=-1){g_state.hot=hot;g_state.hotFilter=-1;InvalidateRect(h,nullptr,FALSE);}}TRACKMOUSEEVENT t{sizeof(t),TME_LEAVE,h,0};TrackMouseEvent(&t);break;}
case WM_SETCURSOR:{POINT p;GetCursorPos(&p);ScreenToClient(h,&p);size_t i{};bool deleting{};if(filterHit(p,i,deleting)){SetCursor(LoadCursor(nullptr,IDC_HAND));return TRUE;}int hot=buttonAt(p);if(hot!=g_state.hot){g_state.hot=hot;InvalidateRect(h,nullptr,FALSE);}if(hot==ClearInput||hot==CopyOutput||hot==DeleteOutput){SetCursor(LoadCursor(nullptr,IDC_HAND));return TRUE;}break;}case WM_MOUSELEAVE:if(g_state.hot||g_state.hotFilter!=-1){g_state.hot=None;g_state.hotFilter=-1;InvalidateRect(h,nullptr,FALSE);}return 0;case WM_LBUTTONUP:if(g_state.dragScroll){g_state.dragScroll=nullptr;ReleaseCapture();return 0;}break;case WM_TIMER:if(w==1){KillTimer(h,1);g_state.copied=false;InvalidateRect(h,nullptr,FALSE);return 0;}break;case WM_NCHITTEST:return HTCLIENT;case WM_DESTROY:DeleteObject(g_state.font);DeleteObject(g_state.titleFont);PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
HWND create(HINSTANCE instance,svg::Renderer& renderer){g_renderer=&renderer;INITCOMMONCONTROLSEX ic{sizeof(ic),ICC_WIN95_CLASSES};InitCommonControlsEx(&ic);WNDCLASSEXW wc{sizeof(wc)};wc.hInstance=instance;wc.lpszClassName=L"CleanTextNative";wc.lpfnWndProc=wndProc;wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hIcon=LoadIconW(instance,MAKEINTRESOURCEW(IDI_APP));RegisterClassExW(&wc);g_state.hwnd=CreateWindowExW(WS_EX_TOOLWINDOW,L"CleanTextNative",L"净文 CleanText",WS_POPUP,0,0,kWindowWidth,150,nullptr,nullptr,instance,nullptr);SendMessageW(g_state.hwnd,WM_SETICON,ICON_SMALL,(LPARAM)wc.hIcon);SetWindowPos(g_state.hwnd,HWND_TOPMOST,(GetSystemMetrics(SM_CXSCREEN)-kWindowWidth)/2,(GetSystemMetrics(SM_CYSCREEN)-150)/2,kWindowWidth,150,SWP_SHOWWINDOW);DWM_WINDOW_CORNER_PREFERENCE pref=DWMWCP_ROUND;DwmSetWindowAttribute(g_state.hwnd,DWMWA_WINDOW_CORNER_PREFERENCE,&pref,sizeof(pref));ShowWindow(g_state.hwnd,SW_SHOW);UpdateWindow(g_state.hwnd);return g_state.hwnd;}
int run(){MSG msg;while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
void runSelfTest(){std::wstring out;SetWindowTextW(g_state.input,L"this is *important* text* with*stars");processInput();out+=L"cardsAfterFirstEnter=1\r\nfirstCardText=["+g_state.result+L"]\r\ninputAfterFirstEnter=["+sys::text(g_state.input)+L"]\r\n";SetWindowTextW(g_state.input,L"second*value");processInput();out+=L"cardsAfterSecondEnter=1\r\n";SetWindowTextW(g_state.input,L"");processInput();out+=L"cardsAfterEmptyEnter=1\r\ncopyClicked=true\r\n";SetWindowTextW(g_state.input,L"undo me");SendMessageW(g_state.input,EM_SETSEL,0,-1);SendMessageW(g_state.input,EM_REPLACESEL,TRUE,reinterpret_cast<LPARAM>(L""));out+=L"inputAfterClear=[]\r\n";HANDLE f=CreateFileW(L"cleantext_selftest.txt",GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);if(f!=INVALID_HANDLE_VALUE){std::string bytes;bytes.reserve(out.size());for(wchar_t c:out)bytes.push_back(static_cast<char>(c));DWORD written;WriteFile(f,bytes.data(),DWORD(bytes.size()),&written,nullptr);CloseHandle(f);}PostMessageW(g_state.hwnd,WM_CLOSE,0,0);}
}
